### ISSUE TITLE
Replacement is mixing up variables

### ISSUE THREAD

**Issue by ericchernuka** [navanshu/postcss-variable-compress#34]
I just tried this plugin out, but I'm getting weird behaviour where variables which are numbers and units are being replaced with colours. I've provided an example below.  Any thoughts?

![image (2)](https://user-images.githubusercontent.com/243155/159589286-ba5cc08f-8ad1-4a39-9c64-45cee6d1fe57.png)

```css
/* index.scss */
:root {
  --ds-transition-property-base: opacity, transform, background-color,
    box-shadow, border-color, color;
  --ds-transition-duration-base: 200ms;
  --ds-transition-timing-function-base: cubic-bezier(0.4, 0, 0.2, 1);
  --ds-border-radius-base: 0.375rem;
  --ds-spacing-tight: 0.5rem;
  --ds-spacing-base: 1rem;
  --ds-font-size-sm: 0.85rem;
  --ds-font-weight-semi-bold: 600;
  --ds-line-height-sm: 1.25rem;
}
```
```css
/* Button.module.scss */
.Button {
  transition-property: var(--ds-transition-property-base);
  transition-duration: var(--ds-transition-duration-base);
  transition-timing-function: var(--ds-transition-timing-function-base);
  position: relative;
  outline: none;
  box-sizing: border-box;
  border: 1px solid transparent;
  border-radius: var(--ds-border-radius-base);
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  padding: var(--ds-spacing-tight) var(--ds-spacing-base);
  text-align: center;
  font-size: var(--ds-font-size-sm);
  font-weight: var(--ds-font-weight-semi-bold);
  line-height: var(--ds-line-height-sm);
}
```
