### ISSUE TITLE
Replace "constants" with their value

### ISSUE THREAD

**Issue by pbb72** [navanshu/postcss-variable-compress#49]
Would it be possible to replace CSS variables that never change, with their value (only if using the value is shorter than using the variable name)?

Based on your own example:

```css
:root {
  --first-color: #16f; /* variable, changes in #container */
  --second-color: #ff7; /* constant, never changes */
  --font: Arial, Helvetica, sans-serif; /* constant, but with a very long value */
}

#firstParagraph {
  background-color: var(--first-color);
  color: var(--second-color);
  font-family: var(--font);
}

#container {
  --first-color: #290;
  font-family: var(--font);
}
```

```css
:root {
  --0: #16f;
  --2: Arial, Helvetica, sans-serif;
}

#firstParagraph {
  background-color: var(--0);
  color: #ff7;
  font-family: var(--2);
}

#container {
  --0: #290;
  font-family: var(--2);
}
```

Removing `--1: #ff7;` and using `#ff7` instead of `var(--1)` saves 9 bytes + 4 bytes per usage of the variable.

Even though the `--font` variable is also constant, it's actually shorter to use a variable. But if the variable would have been used only once, then it would have saved space to replace the variable with it's value.
